/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-13 21:06:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.com.tienda.modelo.entidades.Venta;
import com.com.tienda.modelo.entidades.Producto;

public final class Factura_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.com.tienda.modelo.entidades.Venta");
    _jspx_imports_classes.add("com.com.tienda.modelo.entidades.Producto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Venta venta = (Venta) request.getAttribute("venta");
List<Producto> detalles = (List<Producto>) request.getAttribute("detalles");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Factura</title>\r\n");
      out.write("<style>\r\n");
      out.write("body { font-family: Arial; background: #f5f5f5; padding: 20px; }\r\n");
      out.write(".factura-box { max-width: 800px; margin: auto; background: white; padding: 20px; border-radius: 10px; }\r\n");
      out.write("table { width: 100%; border-collapse: collapse; margin-top: 15px; }\r\n");
      out.write("table, th, td { border: 1px solid #ccc; }\r\n");
      out.write("th, td { padding: 10px; text-align: center; vertical-align: middle; }\r\n");
      out.write("h2 { text-align: center; }\r\n");
      out.write(".total-box { text-align: right; margin-top: 20px; font-size: 20px; }\r\n");
      out.write("a { text-decoration: none; color: white; background: #4CAF50; padding: 10px 15px; border-radius: 5px; }\r\n");
      out.write("\r\n");
      out.write(".producto-img { width: 60px; height: 60px; object-fit: cover; border-radius: 6px; }\r\n");
      out.write(".producto-nombre { display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"factura-box\">\r\n");
      out.write("\r\n");
      out.write("<h2>Factura de Compra</h2>\r\n");
      out.write("\r\n");
      out.write("<p><strong>ID Venta:</strong> ");
      out.print( venta.getId() );
      out.write("</p>\r\n");
      out.write("<p><strong>Cliente (ID Usuario):</strong> ");
      out.print( venta.getIdUsuario() );
      out.write("</p>\r\n");
      out.write("<p><strong>Fecha:</strong> ");
      out.print( venta.getFecha() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("    <th>Producto</th>\r\n");
      out.write("    <th>Precio</th>\r\n");
      out.write("    <th>Cantidad</th>\r\n");
      out.write("    <th>Subtotal</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 for (Producto p : detalles) { 
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <td>\r\n");
      out.write("        <div class=\"producto-nombre\">\r\n");
      out.write("            <img class=\"producto-img\" src=\"");
      out.print( request.getContextPath() );
      out.write("/ImagenProducto?id=");
      out.print( p.getId() );
      out.write("\" alt=\"");
      out.print( p.getNombre() );
      out.write("\">\r\n");
      out.write("            <span>");
      out.print( p.getNombre() );
      out.write("</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>$");
      out.print( p.getPrecio() );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( p.getStock() );
      out.write("</td>\r\n");
      out.write("    <td>$");
      out.print( p.getSubtotal() );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 } 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div class=\"total-box\">\r\n");
      out.write("    <strong>Total: $");
      out.print( venta.getTotal() );
      out.write("</strong>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/tienda\">Volver a la tienda</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
