/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-13 21:05:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.com.tienda.modelo.entidades.Producto;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.com.tienda.modelo.entidades.Producto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<String> categorias = (List<String>) request.getAttribute("categorias");
    List<Producto> productos = (List<Producto>) request.getAttribute("productos");

    if (categorias == null) categorias = new java.util.ArrayList<>();
    if (productos == null) productos = new java.util.ArrayList<>();

    String catActiva = request.getParameter("cat");

    HttpSession ses = request.getSession(false);
    String rol = (ses != null && ses.getAttribute("rol") != null) ? (String) ses.getAttribute("rol") : null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Tienda</title>\r\n");
      out.write("<style>\r\n");
      out.write("body { margin: 0; background: #eef1f7; font-family: \"Segoe UI\", sans-serif; }\r\n");
      out.write("header { background: #ffffff; padding: 18px 40px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 2px 12px rgba(0,0,0,0.06); position: sticky; top: 0; z-index: 100; }\r\n");
      out.write("header h1 { margin: 0; font-size: 26px; font-weight: 700; color: #1a5eff; }\r\n");
      out.write("header a { text-decoration: none; font-weight: 600; margin-left: 20px; padding: 8px 15px; border-radius: 8px; transition: .2s; }\r\n");
      out.write(".login { color: #1a1a1a; }\r\n");
      out.write(".logout { background: #ff4747; color: white; }\r\n");
      out.write(".logout:hover { background: #d63232; }\r\n");
      out.write(".contenedor { display: grid; grid-template-columns: 240px 1fr; gap: 30px; padding: 30px 40px; }\r\n");
      out.write(".sidebar { background: #ffffff; padding: 20px; border-radius: 14px; box-shadow: 0 3px 10px rgba(0,0,0,0.06); }\r\n");
      out.write(".sidebar h3 { margin-top: 0; font-size: 20px; color: #1a5eff; }\r\n");
      out.write(".categoria { display: block; padding: 10px 12px; margin: 6px 0; background: #f4f6fc; border-radius: 8px; text-decoration: none; color: #1a1a1a; font-size: 15px; transition: .25s; }\r\n");
      out.write(".categoria:hover { background: #e3eaff; }\r\n");
      out.write(".categoria-activa { background: #1a5eff; color: white !important; font-weight: bold; }\r\n");
      out.write(".productos { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 25px; }\r\n");
      out.write(".card { background: white; border-radius: 14px; overflow: hidden; box-shadow: 0 3px 12px rgba(0,0,0,0.07); transition: .2s; }\r\n");
      out.write(".card:hover { transform: translateY(-4px); box-shadow: 0 5px 18px rgba(0,0,0,0.12); }\r\n");
      out.write(".card img { width: 100%; height: 185px; object-fit: cover; }\r\n");
      out.write(".info { padding: 15px; }\r\n");
      out.write(".nombre { font-size: 17px; font-weight: 700; margin: 6px 0 4px; }\r\n");
      out.write(".precio { color: #1a5eff; font-size: 18px; margin: 3px 0; font-weight: bold; }\r\n");
      out.write(".stock { font-size: 14px; color: #555; margin-bottom: 10px; }\r\n");
      out.write(".btn { display: block; text-align: center; background: #1a5eff; padding: 10px; margin-top: 10px; border-radius: 8px; color: white; text-decoration: none; font-weight: 600; transition: .2s; }\r\n");
      out.write(".btn:hover { background: #0f42c8; }\r\n");
      out.write(".btn-disabled { background: #9a9a9a !important; pointer-events: none; }\r\n");
      out.write(".login-warning { color: #b30000; font-size: 13px; margin-bottom: 5px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <h1>🛒 Tienda Web</h1>\r\n");
      out.write("    <div>\r\n");
      out.write("        ");
 if (rol == null) { 
      out.write("\r\n");
      out.write("            <a class=\"login\" href=\"login.jsp\">Iniciar sesión</a>\r\n");
      out.write("            <a class=\"login\" href=\"registro.jsp\">Registrarse</a>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <a class=\"logout\" href=\"logout\">Cerrar sesión</a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"contenedor\">\r\n");
      out.write("\r\n");
      out.write("    <!-- SIDEBAR -->\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <h3>Categorías</h3>\r\n");
      out.write("        <a href=\"tienda\" class=\"categoria ");
      out.print( (catActiva == null ? "categoria-activa" : "") );
      out.write("\">Todas</a>\r\n");
      out.write("        ");
 for (String c : categorias) { 
      out.write("\r\n");
      out.write("            <a href=\"tienda?cat=");
      out.print( c );
      out.write("\" class=\"categoria ");
      out.print( (c.equals(catActiva) ? "categoria-activa" : "") );
      out.write('"');
      out.write('>');
      out.print( c );
      out.write("</a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- PRODUCTOS -->\r\n");
      out.write("    <div class=\"productos\">\r\n");
      out.write("        ");
 if (productos.isEmpty()) { 
      out.write("\r\n");
      out.write("            <p>No hay productos en esta categoría.</p>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 for (Producto p : productos) { 
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"");
      out.print( request.getContextPath() );
      out.write("/ImagenProducto?id=");
      out.print( p.getId() );
      out.write("\" alt=\"Producto\">\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                    <div class=\"nombre\">");
      out.print( p.getNombre() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"precio\">$");
      out.print( p.getPrecio() );
      out.write(" USD</div>\r\n");
      out.write("                    <div class=\"stock\">Stock: ");
      out.print( p.getStock() );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (rol == null) { 
      out.write("\r\n");
      out.write("                        <div class=\"login-warning\">Inicia sesión para comprar</div>\r\n");
      out.write("                        <a class=\"btn btn-disabled\">Agregar al carrito</a>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        ");
 if (p.getStock() <= 0) { 
      out.write("\r\n");
      out.write("                            <a class=\"btn btn-disabled\">Agotado</a>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <a class=\"btn\" href=\"carrito?accion=agregar&id=");
      out.print( p.getId() );
      out.write("\">Agregar al carrito</a>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
