/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-16 01:30:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class registro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<String> monedas = new java.util.ArrayList<>();
    monedas.add("COP");
    monedas.add("USD");
    monedas.add("EUR");
    monedas.add("ARS");
    monedas.add("MXN");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Registro</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        height: 100vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        font-family: \"Segoe UI\", Arial, sans-serif;\r\n");
      out.write("        background: linear-gradient(135deg, #74b9ff, #81ecec);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card {\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 40px 35px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        box-shadow: 0 15px 35px rgba(0,0,0,0.18);\r\n");
      out.write("        animation: fadeIn 0.4s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 28px;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        font-weight: 800;\r\n");
      out.write("        color: #2d3436;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input-group {\r\n");
      out.write("        margin-bottom: 18px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #636e72;\r\n");
      out.write("        margin-bottom: 6px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input, select {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 12px 14px;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        border: 2px solid #dfe6e9;\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        transition: 0.25s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input:focus, select:focus {\r\n");
      out.write("        border-color: #0984e3;\r\n");
      out.write("        box-shadow: 0 0 10px rgba(9,132,227,0.35);\r\n");
      out.write("        outline: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 14px;\r\n");
      out.write("        margin-top: 22px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 14px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        background: linear-gradient(135deg, #0984e3, #0570c9);\r\n");
      out.write("        color: white;\r\n");
      out.write("        transition: 0.25s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button:hover {\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        box-shadow: 0 8px 20px rgba(9,132,227,0.4);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeIn {\r\n");
      out.write("        from { opacity: 0; transform: translateY(14px); }\r\n");
      out.write("        to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("    <h2>📝 Crear cuenta</h2>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"registroUsuario\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("            <label>👤 Nombre</label>\r\n");
      out.write("            <input type=\"text\" name=\"nombre\" placeholder=\"Tu nombre completo\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("            <label>📧 Correo electrónico</label>\r\n");
      out.write("            <input type=\"email\" name=\"email\" placeholder=\"correo@ejemplo.com\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("            <label>🔐 Contraseña</label>\r\n");
      out.write("            <input type=\"password\" name=\"password\" placeholder=\"••••••••\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("            <label>💱 Moneda preferida</label>\r\n");
      out.write("            <select name=\"moneda_preferida\" required>\r\n");
      out.write("                ");
 for (String moneda : monedas) { 
      out.write("\r\n");
      out.write("                    <option value=\"");
      out.print( moneda );
      out.write('"');
      out.write('>');
      out.print( moneda );
      out.write("</option>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <input type=\"hidden\" name=\"rol\" value=\"cliente\">\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\">✨ Registrarme</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
