/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-07 00:37:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.tienda.modelo.entidades.Producto;

public final class Tienda_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.tienda.modelo.entidades.Producto");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    List<String> categorias = (List<String>) request.getAttribute("categorias");
    List<Producto> productos = (List<Producto>) request.getAttribute("productos");

    HttpSession s = request.getSession(false);
    String rol = null;

    if (s != null && s.getAttribute("rol") != null) {
        rol = (String) s.getAttribute("rol");
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Tienda</title>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            background: #f4f4f4;\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* CONTENEDOR PRINCIPAL */\n");
      out.write("        .container {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 25px;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* CAJA DE FILTROS */\n");
      out.write("        .sidebar {\n");
      out.write("            width: 220px;\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 20px;\n");
      out.write("            box-shadow: 0 0 10px rgba(0,0,0,0.1);\n");
      out.write("            height: fit-content;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar h3 {\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .categoria-link {\n");
      out.write("            display: block;\n");
      out.write("            margin: 5px 0;\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: #333;\n");
      out.write("            font-size: 15px;\n");
      out.write("            padding: 5px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .categoria-link:hover {\n");
      out.write("            background: #ececec;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* LISTA DE PRODUCTOS */\n");
      out.write("        .productos {\n");
      out.write("            flex: 1;\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* TARJETA PRODUCTO */\n");
      out.write("        .card {\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 15px;\n");
      out.write("            box-shadow: 0 0 10px rgba(0,0,0,0.1);\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card img {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 170px;\n");
      out.write("            object-fit: cover;\n");
      out.write("            border-radius: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card h4 {\n");
      out.write("            margin: 10px 0 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card p {\n");
      out.write("            margin: 5px 0 15px;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* BOTONES */\n");
      out.write("        .btn {\n");
      out.write("            padding: 10px;\n");
      out.write("            background: #0077ff;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: block;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn:hover {\n");
      out.write("            background: #005ace;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-disabled {\n");
      out.write("            background: #777;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-warning {\n");
      out.write("            color: #d10000;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("    <!-- SIDEBAR - FILTRO DE CATEGORÍAS -->\n");
      out.write("    <div class=\"sidebar\">\n");
      out.write("        <h3>Categorías</h3>\n");
      out.write("\n");
      out.write("        <a href=\"tienda\" class=\"categoria-link\">Todas</a>\n");
      out.write("\n");
      out.write("        ");
 for (String cat : categorias) { 
      out.write("\n");
      out.write("            <a href=\"tienda?cat=");
      out.print( cat );
      out.write("\" class=\"categoria-link\">");
      out.print( cat );
      out.write("</a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- PRODUCTOS -->\n");
      out.write("    <div class=\"productos\">\n");
      out.write("\n");
      out.write("        ");
 if (productos.isEmpty()) { 
      out.write("\n");
      out.write("            <p>No hay productos en esta categoría.</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        ");
 for (Producto p : productos) { 
      out.write("\n");
      out.write(" <div class=\"card\">\n");
      out.write("    <img src=\"");
      out.print( p.getImagenURL() );
      out.write("\" alt=\"Imagen producto\">\n");
      out.write("\n");
      out.write("    <h4>");
      out.print( p.getNombre() );
      out.write("</h4>\n");
      out.write("    <p>Precio: $");
      out.print( p.getPrecioUSD() );
      out.write(" USD</p>\n");
      out.write("    <p>Stock: ");
      out.print( p.getStock() );
      out.write("</p>\n");
      out.write("\n");
      out.write("    ");
 if (rol == null) { 
      out.write("\n");
      out.write("        <!-- Usuario NO logueado -->\n");
      out.write("        <p class=\"login-warning\">Debes iniciar sesión para comprar</p>\n");
      out.write("        <a class=\"btn btn-disabled\" href=\"login.jsp\">Iniciar Sesión</a>\n");
      out.write("\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("        <!-- Usuario logueado (cliente o admin) -->\n");
      out.write("         <a class=\"btn\" href=\"carrito?accion=agregar&id=");
      out.print( p.getId() );
      out.write("\">Agregar al carrito</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
