/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-13 21:06:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.com.tienda.modelo.entidades.Producto;
import com.com.tienda.modelo.dao.CarritoDAO;
import java.util.List;

public final class VerCarrito_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.com.tienda.modelo.dao.CarritoDAO");
    _jspx_imports_classes.add("com.com.tienda.modelo.entidades.Producto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

CarritoDAO carritoDAO = new CarritoDAO();
List<Producto> carrito = (List<Producto>) request.getAttribute("carrito");
if (carrito == null) carrito = new java.util.ArrayList<>();

double totalGeneral = 0;
for (Producto p : carrito) totalGeneral += p.getPrecio() * p.getStock();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Carrito</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body { margin: 0; background: #f2f6ff; font-family: 'Segoe UI', sans-serif; }\r\n");
      out.write(".container { width: 90%; max-width: 1000px; margin: 40px auto; padding: 20px; }\r\n");
      out.write(".card { background: white; padding: 25px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }\r\n");
      out.write("h1 { text-align: center; color: #243b72; margin-bottom: 25px; font-size: 32px; font-weight: 700; }\r\n");
      out.write("table { width: 100%; border-collapse: collapse; margin-top: 10px; }\r\n");
      out.write("table thead { background: #243b72; color: white; }\r\n");
      out.write("table th, table td { padding: 14px; text-align: center; vertical-align: middle; }\r\n");
      out.write("table tbody tr:hover { background: #eef3ff; transition: .2s; }\r\n");
      out.write("table img { width: 80px; height: 80px; object-fit: cover; border-radius: 8px; }\r\n");
      out.write("input[type=\"number\"] { width: 65px; padding: 6px; border: 1px solid #bbb; border-radius: 6px; text-align: center; }\r\n");
      out.write(".btn { display: inline-block; padding: 12px 18px; margin: 10px 8px 0 0; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 15px; transition: 0.25s; cursor: pointer; }\r\n");
      out.write(".btn-blue { background: #243b72; color: white; }\r\n");
      out.write(".btn-blue:hover { background: #1a2c55; }\r\n");
      out.write(".btn-green { background: #1da874; color: white; }\r\n");
      out.write(".btn-green:hover { background: #157c56; }\r\n");
      out.write(".btn-red { background: #d62828; color: white; }\r\n");
      out.write(".btn-red:hover { background: #a81f1f; }\r\n");
      out.write("tfoot td { font-weight: bold; background: #dce5ff; padding: 16px; font-size: 18px; border-top: 2px solid #243b72; }\r\n");
      out.write(".actions { margin-top: 25px; text-align: center; }\r\n");
      out.write(".producto-nombre { display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("<h1>? Tu carrito de compras</h1>\r\n");
      out.write("\r\n");
      out.write("<form action=\"carrito\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("    <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>ID</th>\r\n");
      out.write("            <th>Producto</th>\r\n");
      out.write("            <th>Precio</th>\r\n");
      out.write("            <th>Cantidad</th>\r\n");
      out.write("            <th>Total</th>\r\n");
      out.write("            <th>Quitar</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("\r\n");
      out.write("    <tbody>\r\n");
      out.write("        ");
 for (Producto p : carrito) { 
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>");
      out.print( p.getId() );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <div class=\"producto-nombre\">\r\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/ImagenProducto?id=");
      out.print( p.getId() );
      out.write("\" alt=\"");
      out.print( p.getNombre() );
      out.write("\">\r\n");
      out.write("                    <span>");
      out.print( p.getNombre() );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>$");
      out.print( p.getPrecio() );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <input type=\"number\"\r\n");
      out.write("                       name=\"cantidad_");
      out.print( p.getId() );
      out.write("\"\r\n");
      out.write("                       value=\"");
      out.print( p.getStock() );
      out.write("\"\r\n");
      out.write("                       min=\"1\"\r\n");
      out.write("                       max=\"");
      out.print( carritoDAO.obtenerStockProducto(p.getId()) );
      out.write("\">\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>$");
      out.print( p.getPrecio() * p.getStock() );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <a class=\"btn btn-red\"\r\n");
      out.write("                   href=\"carrito?accion=eliminar&id=");
      out.print( p.getId() );
      out.write("\"\r\n");
      out.write("                   onclick=\"return confirm('¿Seguro que deseas eliminar este producto?');\">\r\n");
      out.write("                    ?\r\n");
      out.write("                </a>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("\r\n");
      out.write("    <tfoot>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"4\">TOTAL GENERAL</td>\r\n");
      out.write("            <td>$");
      out.print( totalGeneral );
      out.write("</td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </tfoot>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div class=\"actions\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-blue\">Actualizar carrito</button>\r\n");
      out.write("    <a href=\"tienda\" class=\"btn btn-blue\">Seguir comprando</a>\r\n");
      out.write("    <a href=\"carrito?accion=vaciar\" class=\"btn btn-red\">Vaciar carrito</a>\r\n");
      out.write("    <a href=\"carrito?accion=comprar\" class=\"btn btn-green\">Finalizar compra</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
