/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-08 07:29:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.com.tienda.modelo.entidades.Producto;
import com.com.tienda.modelo.dao.CarritoDAO;
import java.util.List;

public final class VerCarrito_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.com.tienda.modelo.dao.CarritoDAO");
    _jspx_imports_classes.add("com.com.tienda.modelo.entidades.Producto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    CarritoDAO carritoDAO = new CarritoDAO();
    List<Producto> carrito = (List<Producto>) request.getAttribute("carrito");
    if (carrito == null) {
        carrito = new java.util.ArrayList<>();
    }

    double totalGeneral = 0;
    for (Producto p : carrito) {
        totalGeneral += p.getPrecio() * p.getStock();
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Carrito de Compras</title>\n");
      out.write("    <style>\n");
      out.write("        body { background: #f4f4f4; font-family: Arial, sans-serif; padding: 20px; margin: 0; }\n");
      out.write("        h1 { text-align: center; color: #0077ff; }\n");
      out.write("        table { width: 80%; margin: 20px auto; border-collapse: collapse; background: white; box-shadow: 0 0 10px rgba(0,0,0,0.1); }\n");
      out.write("        table th, table td { padding: 12px; text-align: center; border-bottom: 1px solid #ddd; }\n");
      out.write("        table th { background-color: #0077ff; color: white; }\n");
      out.write("        table tr:hover { background-color: #f1f1f1; }\n");
      out.write("        table tfoot td { font-weight: bold; background-color: #e8f0ff; }\n");
      out.write("        input[type=\"number\"] { width: 60px; text-align: center; }\n");
      out.write("        .btn { display: inline-block; padding: 10px 15px; margin: 10px 5px; background-color: #0077ff; color: white; text-decoration: none; border-radius: 5px; font-weight: bold; transition: background 0.3s; }\n");
      out.write("        .btn:hover { background-color: #005ace; }\n");
      out.write("        .btn-danger { background-color: #d10000; }\n");
      out.write("        .btn-danger:hover { background-color: #a00000; }\n");
      out.write("        .links-container { text-align: center; margin-top: 20px; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h1>Tu carrito</h1>\n");
      out.write("\n");
      out.write("<form action=\"carrito\" method=\"post\">\n");
      out.write("    <table>\n");
      out.write("        <tr>\n");
      out.write("            <th>ID</th>\n");
      out.write("            <th>Nombre</th>\n");
      out.write("            <th>Precio</th>\n");
      out.write("            <th>Cantidad</th>\n");
      out.write("            <th>Total</th>\n");
      out.write("            <th>Eliminar</th>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("        ");
 for (Producto p : carrito) { 
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>");
      out.print( p.getId() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( p.getNombre() );
      out.write("</td>\n");
      out.write("            <td>$");
      out.print( p.getPrecio() );
      out.write("</td>\n");
      out.write("            <td>\n");
      out.write("                <input type=\"number\" \n");
      out.write("                       name=\"cantidad_");
      out.print( p.getId() );
      out.write("\" \n");
      out.write("                       value=\"");
      out.print( p.getStock() );
      out.write("\" \n");
      out.write("                       min=\"1\" \n");
      out.write("                       max=\"");
      out.print( carritoDAO.obtenerStockProducto(p.getId()) );
      out.write("\">\n");
      out.write("            </td>\n");
      out.write("            <td>$");
      out.print( p.getPrecio() * p.getStock() );
      out.write("</td>\n");
      out.write("            <td>\n");
      out.write("                <a href=\"carrito?accion=eliminar&id=");
      out.print( p.getId() );
      out.write("\" \n");
      out.write("                   class=\"btn btn-danger\"\n");
      out.write("                   onclick=\"return confirm('¿Eliminar este producto del carrito?');\">X</a>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <tfoot>\n");
      out.write("            <tr>\n");
      out.write("                <td colspan=\"4\">TOTAL GENERAL</td>\n");
      out.write("                <td>$");
      out.print( totalGeneral );
      out.write("</td>\n");
      out.write("                <td></td>\n");
      out.write("            </tr>\n");
      out.write("        </tfoot>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <div class=\"links-container\">\n");
      out.write("        <button type=\"submit\" class=\"btn\">Actualizar Carrito</button>\n");
      out.write("        <a href=\"logout\" class=\"btn\">Cerrar Sesión</a>\n");
      out.write("        <a href=\"tienda\" class=\"btn\">Regresar a la Tienda</a>\n");
      out.write("        <a href=\"carrito?accion=vaciar\" class=\"btn btn-danger\">Vaciar carrito</a>\n");
      out.write("    </div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
