/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-15 07:25:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.com.tienda.modelo.entidades.Producto;
import com.com.tienda.modelo.entidades.Usuario;
import java.util.List;

public final class productos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.com.tienda.modelo.entidades.Usuario");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.com.tienda.modelo.entidades.Producto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Productos</title>\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("    --bg: #f0f2f5; --card: #ffffff; --primary: #4a6cf7; --primary-dark: #3854c8;\r\n");
      out.write("    --danger: #ff4d4f; --danger-dark: #cc3d3f; --text: #2c2c2c; --subtext: #666; --shadow: rgba(0,0,0,0.12);\r\n");
      out.write("}\r\n");
      out.write("body { margin: 0; padding: 0; background: var(--bg); font-family: \"Segoe UI\", Arial, sans-serif; }\r\n");
      out.write("h1 { text-align: center; margin: 30px 0 10px; font-size: 42px; letter-spacing: -1px; color: var(--primary-dark); font-weight: 900; }\r\n");
      out.write(".header-links { display: flex; justify-content: center; gap: 20px; margin-bottom: 25px; }\r\n");
      out.write(".btn { padding: 12px 20px; border-radius: 8px; background: var(--primary); color: white; text-decoration: none; font-weight: 600; transition: 0.25s; box-shadow: 0 3px 8px var(--shadow); }\r\n");
      out.write(".btn:hover { background: var(--primary-dark); transform: translateY(-2px); }\r\n");
      out.write(".btn-danger { background: var(--danger); }\r\n");
      out.write(".btn-danger:hover { background: var(--danger-dark); }\r\n");
      out.write(".grid { max-width: 1200px; margin: 0 auto; padding: 10px; display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 25px; }\r\n");
      out.write(".product-card { background: var(--card); border-radius: 15px; padding: 15px; box-shadow: 0 6px 15px var(--shadow); display: flex; flex-direction: column; transition: 0.3s; }\r\n");
      out.write(".product-card:hover { transform: translateY(-5px); box-shadow: 0 10px 20px var(--shadow); }\r\n");
      out.write(".product-img { width: 100%; height: 170px; border-radius: 12px; background-size: cover; background-position: center; margin-bottom: 10px; }\r\n");
      out.write(".product-name { font-size: 20px; font-weight: 700; color: var(--text); margin-bottom: 5px; }\r\n");
      out.write(".product-price { font-size: 18px; font-weight: bold; color: var(--primary-dark); margin-bottom: 10px; }\r\n");
      out.write(".product-actions { margin-top: auto; display: flex; gap: 8px; }\r\n");
      out.write(".empty-msg { text-align: center; font-size: 20px; color: var(--subtext); margin-top: 50px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

    Usuario u = (Usuario) session.getAttribute("usuario");
    if (u == null) { response.sendRedirect("login.jsp"); return; }
    List<Producto> lista = (List<Producto>) request.getAttribute("productos");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>Catálogo de Productos</h1>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-links\">\r\n");
      out.write("    <a href=\"NuevoProducto.jsp\" class=\"btn\">➕ Agregar Producto</a>\r\n");
      out.write("    <a href=\"tienda\" class=\"btn\">🛒 Ir a la Tienda</a> <!-- 🔥 Botón agregado -->\r\n");
      out.write("    <a href=\"logout\" class=\"btn btn-danger\">Cerrar Sesión</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"grid\">\r\n");

if (lista != null && !lista.isEmpty()) {
    for (Producto p : lista) {

      out.write("\r\n");
      out.write("    <div class=\"product-card\">\r\n");
      out.write("        <div class=\"product-img\" style=\"background-image: url('ImagenProducto?id=");
      out.print( p.getId() );
      out.write("');\"></div>\r\n");
      out.write("        <div class=\"product-name\">");
      out.print( p.getNombre() );
      out.write("</div>\r\n");
      out.write("        <div class=\"product-price\">$");
      out.print( p.getPrecio() );
      out.write("</div>\r\n");
      out.write("        <div class=\"product-actions\">\r\n");
      out.write("            <a href=\"editarProducto?id=");
      out.print( p.getId() );
      out.write("\" class=\"btn\" style=\"flex:1;\">Editar</a>\r\n");
      out.write("            <a href=\"EliminarProducto?id=");
      out.print( p.getId() );
      out.write("\" onclick=\"return confirm('¿Eliminar este producto?');\" class=\"btn btn-danger\" style=\"flex:1;\">Eliminar</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");

    }
} else {

      out.write("\r\n");
      out.write("<div class=\"empty-msg\">No hay productos disponibles.</div>\r\n");

}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
